[workspace]
members = ["apps/api", "apps/domain"]
resolver = "2"

[profile.release]
lto = "thin"
strip = true
codegen-units = 1

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
unwrap_used = "warn"
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
